config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "welcome#index"

  resources :user_stocks, only: [:create, :destroy]
  resources :users, only: [:show]
  resources :friendships

  get 'my_portfolio', to:"users#my_portfolio"
  get 'search_stocks', to: "stocks#search"
  get 'my_friends', to: "users#my_friends"
  get 'search_friends', to: "users#search"
  post 'add_friend', to: "users#add_friend"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

# == Schema Information
#
# Table name: friendships
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  friend_id  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/stock.rb
class Stock < ApplicationRecord

  has_many :user_stocks
  has_many :users, through: :user_stocks

  def self.find_by_ticker(ticker_symbol)
    where(ticker: ticker_symbol).first
  end

  def self.new_form_lookup(ticker_symbol)
    begin
      looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
      # price = stripe_commas(looked_up_stock.latest_price)
      # new(name: looked_up_stock.company_name, ticker: looked_up_stock.symbol, last_price: price)
      new(name: looked_up_stock.company_name, ticker: looked_up_stock.symbol, last_price: looked_up_stock.latest_price)
    rescue Exception => e
      return nil
    end
  end

  # def self.stripe_commas(number)
  #     number.gsub(",", "")
  # end
end

# == Schema Information
#
# Table name: stocks
#
#  id         :integer          not null, primary key
#  ticker     :string
#  name       :string
#  last_price :decimal(, )
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/models/user.rb
class User < ApplicationRecord

  mount_uploader :avatar, AvatarUploader
  serialize :avatar, JSON

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
  :recoverable, :rememberable, :validatable

  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  def full_name
    return "#{first_name} #{last_name}".strip if first_name || last_name
    "Anonymous"
  end

  def stock_already_added?(ticker_symbol)
    stock = Stock.find_by_ticker(ticker_symbol)
    return false unless stock
    user_stocks.where(stock_id: stock.id).exists?
  end

  def under_stock_limit?
    (user_stocks.count < 10)
  end

  def can_add_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_added?(ticker_symbol)
  end

  def self.search(param)
    param.strip!
    param.downcase!
    to_send_back = (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_matches(param)
    matches('first_name', param)
  end

  def self.last_name_matches(param)
    matches('last_name', param)
  end

  def self.email_matches(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    User.where("#{field_name} LIKE ?", "%#{param}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
  end
end

# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  first_name             :string
#  last_name              :string
#

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

# == Schema Information
#
# Table name: user_stocks
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  stock_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    # deprecated
    # devise_parameter_sanitizer.for(:sign_up).push(:first_name, :last_name)
    # devise_parameter_sanitizer.for(:account_update).push(:first_name, :last_name)

    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :avatar, :remove_avatar])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def destroy
    @friendship = current_user.friendships.where(friend_id: params[:id]).first
    @friendship.destroy
    flash[:notice] = "Friend was successfully removed."
    redirect_to my_friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController


  def search
    if params[:stock].blank?
      flash.now[:danger] = "You have entered empty search string"
    else
      @stock = Stock.new_form_lookup(params[:stock])
      # render json: @stock
      flash.now[:danger] = "You have entered an incorrect symbol" unless @stock
    end
    respond_to do |format|
      format.js { render partial: 'users/result' }
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.find_by_ticker(params[:stock_ticker])

    if stock.blank?
      stock = Stock.new_form_lookup(params[:stock_ticker])
      stock.save
    end

    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:success] = "Stock #{@user_stock.stock.name} was successfully added to portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    @user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    @user_stock.destroy
    flash[:notice] = "Stock was successfully removed from portfolio."
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def my_portfolio
    @user = current_user
    @user_stocks = current_user.stocks
  end

  def my_friends
    @friendships = current_user.friends
  end

  def search
    if params[:search_param].blank?
      flash.now[:danger] = "You have entered empty search string"
    else
      @users = User.search(params[:search_param])
      @users = current_user.except_current_user(@users)
      flash.now[:danger] = "No users match this search criteria" if @users.blank?
    end
    respond_to do |format|
      format.js { render partial: 'friends/result' }
    end
  end

  def add_friend
    @friend = User.find(params[:friend])
    current_user.friendships.build(friend_id: @friend.id)

    if current_user.save
      flash[:success] = "Friend was successfully added."
    else
      flash[:danger] = "There was something wrong with the friend request"
    end

    redirect_to my_friends_path
  end

  def show
    @user = User.find(params[:id])
    @user_stocks = @user.stocks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/views/friends/_lookup.haml
%h1 My Friends
%h3 Search for Friends
#friend-lookup
  = form_tag search_friends_path, remote: true, method: :get, id: "friend-lookup-form" do
    .form-group.row.no-padding.text-center.col-md-12
      .col-md-10
        = text_field_tag :search_param, params[:search_param], placeholder: "Enter name or email", autofocus: true, class: "form-control search-box input-lg"
      .col-md-2
        = button_tag(type: :submit, class: "btn btn-lg btn-success") do
          %i.fa.fa-search
          Search
#results
  = render 'friends/result'

app/views/friends/_result.haml
- if params[:action] == 'search'
  .results-block
    = bootstrap_flash
- if @users
  - if @users.size > 0
    #friend-lookup-results.well.results-block.col-md-10
      %table.search-results-table.col-md-12
        %tbody
          - @users.each do |user|
            %tr
              %td
                %strong Name:
                = user.full_name
              %td
                %strong Email:
                = user.email
              %td
                %strong Profile:
                = link_to "View Profile", user_path(user), class: "btn btn-xs btn-success"
                - if current_user.not_friends_with?(user.id)
                  = link_to "Add as my friend", add_friend_path(user: current_user, friend: user), class: "btn btn-xs btn-success", method: :post
                - else
                  %span.label.label-primary
                    You are already friends

app/views/friends/_result.js.erb
$("#results").html("<%= j (render 'friends/result.haml') %>")

app/views/layouts/_navigation.haml
.navbar.navbar-default.navbar-static-top
  .container
    = link_to "FinanceTracker", root_path, class: "navbar-brand"
    - if current_user
      %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .navbar-collapse.collapse.navbar-responsive-collapse
        %ul.nav.navbar-nav.col-md-6
          %li= link_to "My Portfolio", my_portfolio_path
          %li= link_to "My Profile", edit_user_registration_path
          %li= link_to "My Friends", my_friends_path
        %ul.nav.navbar-right.col-md-4
          %li.col-md-8.user-name.text-right
            %i.fa.fa-user
            = current_user.full_name.present? ? current_user.full_name : current_user.email
          %li.col-md-4.logout
            = link_to "Log out", destroy_user_session_path, class: "btn btn-xs btn-danger", method: :delete

app/views/layouts/application.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "FinanceTracker"
    = csrf_meta_tags
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
  %body
    = render 'layouts/navigation'
    .container
      .row
        .col-lg-9
          = bootstrap_flash
          = yield
      %footer
        %p © Company 2019

app/views/stocks/_list.haml
%table.table.table-stripped
  %thead
    %tr
      %th Name
      %th Symbol
      %th Current price
      - if @user.id == current_user.id
        %th Actions
  %tbody
    - @user_stocks.each do |user_stock|
      %tr
        %td= user_stock.name
        %td= user_stock.ticker
        %td= user_stock.last_price
        - if (@user.id == current_user.id)
          %td= link_to "Delete this stock?", user_stock_path(user_stock), method: :delete, data: { confirm: "Are You sure?" }, class: "btn btn-xs btn-danger"

app/views/users/_result.haml
- if params[:action] == 'search'
  .results-block
    = bootstrap_flash
- if @stock
  .well.results-block
    %strong Symbol:
    = @stock.ticker
    %strong Name:
    = @stock.name
    %strong Price:
    = @stock.last_price
    - if current_user.can_add_stock?(@stock.ticker)
      = link_to "Add to my stocks", user_stocks_path(user: current_user, stock_ticker: @stock.ticker), class: "btn btn-xs btn-success", method: :post
    - else
      %span.label.label-default
        Stock cannot be added because you have already added
        - if !current_user.under_stock_limit?
          10 stocks
        - if current_user.stock_already_added?(@stock.ticker)
          this stock

app/views/users/_result.js.erb
$("#results").html("<%= j (render 'users/result.haml') %>")

app/views/users/my_friends.haml
= render 'friends/lookup'
- if @friendships.size > 0
  %table.table.table-striped
    %thead
      %tr
        %th.page-header{:colspan => "3"}
          %h2 My Friends
      %tr
        %th Name
        %th Email
        %th Actions
    %tbody
      - @friendships.each do |friend|
        %tr
          %td= friend.full_name
          %td= friend.email
          %td
            = link_to "View Profile", user_path(friend), class: "btn btn-primary btn-xs"
            = link_to "Remove Friend", friendship_path(friend), method: :delete, |
              data: { confirm: "Are you sure?" }, class: "btn btn-xs btn-danger" |
- else
  .row.col-lg-12
    %p.lead
      You don't have any friends yet, please add some!

app/views/users/my_portfolio.haml
%h1 My Portfolio
%h3 Search for Stocks
#stock-lookup
  = form_tag search_stocks_path, remote: true, method: :get, id: "stock-lookup-form" do
    .form-group.row.no-padding.text-center.col-md-12
      .col-md-10
        = text_field_tag :stock, params[:stock], placeholder: "Stock ticker symbol", autofocus: true, class: "form-control search-box input-lg"
      .col-md-2
        = button_tag(type: :submit, class: "btn btn-lg btn-success") do
          %i.fa.fa-search
          Look up a stock
#results
  = render 'users/result'
= render 'stocks/list'

app/views/users/show.haml
%h2 User Details
%dl.dl-horizontal
  %dt
    %strong Full Name
  %dd= @user.full_name
  %dt
    %strong Email
  %dd= @user.email
- if @user.stocks.size > 0
  = render 'stocks/list'
- else
  %p.lead This user is not tracking any stocks
= link_to "Back", my_friends_path, class: "btn btn-primary"

app/views/welcome/index.haml
%h1 Welcome to the finance tracker app